### PR TITLE
235: Configuration file

### PR DESCRIPTION
**Pull request by charles-turner-1**
+ Added a catalog-configure console script
+ Tests for behaviour
    - Copies a config.yaml file from `$ROOT/data/config.yaml` to `$HOME/.catalog/config.yaml`.
    - If `$HOME/.catalog/config.yaml`, require -f/--force flag to copy.
    - To specify version, we use the -v/--version flag.
    - To specify interactive mode, we use -i/--interactive flag (currently disabled/ raises SystemExit).

### CODE REVIEW

**Comment by charles-turner-1** [comment]
Closes #235.

@rbeucher I haven't added an interactive mode but I think a (very) basic TUI which steps the user through the config file, shows them current values/defaults & lets them update it if they wish would like would improve this feature.

I also haven't added any validation of the version number as I don't know what sort of versioning we're planning to use for this.

**Comment by marc-white** [comment]
I'm not clear on what this configuration file is actually specifying. Is it trying to set a default value for the catalog version, i.e., set an intrinsic default for 

```python
cat = intake.cat.access_nri(version=NNN)
```

**Comment by charles-turner-1** [comment]
Yup, I think so - I haven't added any of the functionality to address the catalog versioning, but the aim would be to have the default catalog version set (in `data/config.yaml`). 

If the user has specified a catalog version they're after, using eg. `$ catalog-configure -v  X.X.X`, then they'll have a `~/.catalog/config` file - which we can then get the package to read preferentially over `data/config.yaml` to load that specific catalog version.

I think that was where the the discussion was leading in #191? I may have completely misunderstood...

**Comment by marc-white** [comment]
I think there's been a crossed wire somewhere here. A user doesn't _necessarily_ need a separate config file to be able to access different catalog versions - simply passing the `version` kwarg to `intake.cat.access_nri` should do it.

**However**, this rule is broken if the catalog versions are different in structure (`columns_with_iterables`), location of the catalog CSV file (`path`), storage requirements (`metadata.storage`), etc. Then, a different `catalog.yaml` will need to be hooked into `access_nri_intake_catalog.data.data` to get the `intake.cat.access_nri` load working correctly.

I can imagine these `catalog.yaml` files living in the same `/g/data/xp65` location at the catalog CSVs do, and the package can be told that's where they are. The question is then, what to do if, for whatever reason, you can't access `xp65`?

- As @rbeucher has suggested back in #191 , a user might want to be able to provide their own specification for the catalog, for example if they've set up their own mini-ACCESS_NRI catalog in their own storage for some reason. In that case, they'd need a system to be able to point `access_nri.data.data` at the right place. That being said, I'm not entirely sure why a user would want to create their own version of `access_nri_intake_catalog` - conceivably, if they know what they want out of their own data, they could just access it directly...
- If neither of these options are found, we could fail out with some sort of Catalog Not Found error.

If we do want to provide the user with a template `catalog.yaml` to be dumped into their home area, it should be a template, or a reference to some location where a `catalog.yaml` exists.

**Comment by charles-turner-1** [comment]
Yup, it looks an awful lot like I've misunderstood something crucial here. I'm gonna go back through and make sure I understand exactly what's going on at the point of intake.cat.access_nri attribute access.

I've marked this as draft for now, rather than closing it - might be something of use here.

**Pull request closed without merging**
