### PR TITLE
214 era 5 data request

### PR DESCRIPTION
**Pull request by charles-turner-1**
- Added ERA5 Translator & tests for translated data.
- Moved test for 'tuplify_series' decorator to a more sensible spot in `test_translators.py`

### Note

Still a bunch of additional commits in here relating to #212 as this branch was opened before we finished merging that so we'll need to be careful to clean those out in the squashed commit message.

### CODE REVIEW

**Comment by charles-turner-1** [comment]
@rbeucher are you able to review?

**Comment by rbeucher** [comment]
Yes I will

**Review by rbeucher — APPROVED** [review]
Looks good to me! I noticed some discrepancies where certain PRs point to /g/data/xp65/admin/intake and others to /g/data/xp65/admin/access-nri-intake-catalog. We’ll need to double-check these paths before the release.

**Comment by charles-turner-1** [comment]
> Looks good to me! I noticed some discrepancies where certain PRs point to /g/data/xp65/admin/intake and others to /g/data/xp65/admin/access-nri-intake-catalog. We’ll need to double-check these paths before the release.

Sounds good - I'll add a note to #230.

**Comment by charles-turner-1** [comment]
Closes #214

**Pull request merged**
