### PR TITLE
Add support for BARPA py18 data store

### PR DESCRIPTION
**Pull request by rbeucher**
This is my first attempt at adding an NCI ESM Datastore to the catalog.
I have started playing with the translators which, I think, could be refactored.

### CODE REVIEW

**Comment by charles-turner-1** [comment]
I'll run through this later this afternoon - I'm not overly familiar with the process of adding datastores yet so will probably take me a couple hours - I'm planning to use it to understand the process properly

**Review by charles-turner-1 — APPROVED** [review]

**Comment by rbeucher** [comment]
Thanks @charles-turner-1

**Comment by charles-turner-1** [comment]
Closes #211

**Comment by charles-turner-1** [comment]
Closes #197

**Pull request merged**
