### PR TITLE
Remove EraiTranslator and erai catalogs

### LINKED ISSUE #224: [BUG] Missing ERAI `metadata.yaml`
# Describe the bug

In `config/era.yaml`, we have

```yaml
builder: null

translator: EraiTranslator

sources:

  - metadata_yaml: /g/data/tm70/intake/metadata/erai/metadata.yaml
    path:
      - /g/data/hh5/public/apps/nci-intake-catalogue/erai/catalogue.json
```

However, the metadata_yaml file (` /g/data/tm70/intake/metadata/erai/metadata.yaml`) doesn't exist, nor can it be found in `/g/data/xp65/admin/intake/`:
```bash
[ct1163@gadi-login-06 metadata]$ cd /g/data/xp65/admin/intake/metadata/
[ct1163@gadi-login-06 metadata]$ tree .
.
├── cmip5_al33
│   └── metadata.yaml
├── cmip5_rr3
│   └── metadata.yaml
├── cmip6_fs38
│   └── metadata.yaml
├── cmip6_ig45
│   └── metadata.yaml
├── cmip6_oi10
│   └── metadata.yaml
├── cordex_ig45
│   └── metadata.yaml
└── rcm_ccam_hq89
    └── metadata.yaml

7 directories, 7 files
```

I'm assuming this is related to #200.
# To Reproduce

On Gadi, run 
```bash
cat /g/data/tm70/intake/metadata/erai/metadata.yaml
```
# Additional context

I noticed this when trying to figure out what to put in the model field for the metadata.yaml for #214.

### PR DESCRIPTION
**Pull request by marc-white**
Closes #224 .

The ERA catalogues on hh5 will disappear going forward. As the `erai.yaml` catalog file was already being excluded from the catalog build process, it was decided it was time to remove it completely, as well as the related `Translator` (noting the catalogs were pre-built, so there is no associated `Builder`).

### CODE REVIEW

**Review by charles-turner-1 — COMMENTED** [review]
Looks good to me.

One minor comment - I checked out the branch and grepped for erai|ERA Interim.

In our test data, we still have erai.json & erai.csv. I'm 50/50 on whether we should remove these files too?

**Review by rbeucher — CHANGES_REQUESTED** [review]
Let's remove the test data.

**Comment by marc-white** [comment]
Good catch @charles-turner-1 , data removed.

**Review by charles-turner-1 — APPROVED** [review]

**Review by charles-turner-1 — APPROVED** [review]

**Comment by charles-turner-1** [comment]
Looks like I can't approve @rbeucher's requested changes - all looks good to me though.

**Comment by marc-white** [comment]
I think @rbeucher is required to tick that his requested changes have been made. Look at us discovering new GitHub functionality!

**Comment by dougiesquire** [comment]
@charles-turner-1 I've made you admin on this repo. @marc-white, you were already admin.

**Review by rbeucher — APPROVED** [review]

**Pull request merged**
